options:
  restcomm:
    type: string
    default: ""
    description: "install restcomm"
  build_restcomm:
    type: string
    default: ""
    description: "to build or not to build"
  mediaserver:
    type: string
    default: ""
    description: "install_mediaserver"
  build_mediaserver:
    type: string
    default: ""
    description: "to build or not to build"
  mediaserver_port:
    type: string
    default: "2426"
    description: mediaserver port
