#!/bin/bash
set -x

[ -f lib/mobicents/mediaserver-utils.sh ] && . lib/mobicents/mediaserver-utils.sh
[ -f lib/mobicents/restcomm-utils.sh ] && . lib/mobicents/restcomm-utils.sh

initial_mediaserver_config() {
  stop_mediaserver
  uninstall_mediaserver
  [ -n "$(config-get build_mediaserver)" ] && build_mediaserver || download_mediaserver
}
[ -n "$(config-get mediaserver)" ] && initial_mediaserver_config

initial_restcomm_config() {
  stop_restcomm
  uninstall_restcomm
  [ -n "$(config-get build_restcomm)" ] && build_restcomm || download_restcomm
}
[ -n "$(config-get restcomm)" ] && initial_restcomm_config

exit 0

