#!/bin/bash
set -x

[ -f lib/mobicents/mediaserver-utils.sh ] && . lib/mobicents/mediaserver-utils.sh

# this service is now a mediaserver
# this hook should install/config/run mediaserver
update_mediaserver_config() {
  stop_mediaserver
  uninstall_mediaserver
  build_mediaserver
  install_mediaserver
  configure_mediaserver
  restart_mediaserver
}
update_mediaserver_config

# tell the other side
mediaserver_port="2427"
`relation-set port=$mediaserver_port`

exit 0
