#!/bin/bash
set -x

[ -f lib/mobicents/restcomm-utils.sh ] && . lib/mobicents/restcomm-utils.sh

# this side of the relation makes the service act as a restcomm service

# gets mediaserver host/port from remote end
mediaserver_port=`relation-get port`
[ -n "$mediaserver_port" ] || exit 0

mediaserver_host=`relation-get private-address`
mediaserver_address=`dig +short $mediaserver_host`

# this hook should config/run restcomm
update_restcomm_config() {
  [ -n "$mediaserver_address" ] && configure_restcomm $mediaserver_address
  restart_restcomm
}
update_restcomm_config

