#!/bin/bash
set -x

[ -f lib/mobicents/restcomm-utils.sh ] && . lib/mobicents/restcomm-utils.sh

# this side of the relation makes the service act as a restcomm service

# gets mediaserver host/port from remote end
mediaserver_port=`relation-get port`
[ -n "$mediaserver_port" ] || exit 0

# this hook should config/run restcomm
update_restcomm_config() {
  configure_restcomm $mediaserver_port

  # write mediaserver_port to config file conf/restcomm.xml

  restart_restcomm
}
update_restcomm_config

